### ISSUE TITLE
Product Review 0

### ISSUE THREAD

**Issue by ebisennet** [chiroruxx/aiit-student-profile#1]
# なにを作るか
• 自由に考えよ
   - ★ 自己紹介ページ（前略プロフィール的なもの）
      - aiit-student-profile 👆`AIIT 学生プロフィール`

・なぜ作るのか？
   - グループワーク毎に自己紹介するのが手間。自己紹介的なツールで簡略化できるものを作りたいため。

# どのように作るか
• 利用する技術など
    - 言語: Ruby
    - フレームワーク: Ruby on Rails
    - ソースコード共有: GitHub
    - CI/CD: GitHub Action
    - アプリケーションサーバー: Heroku
　-  チケット管理:  GitHub Issueで一旦
　-  コミュニケーションツール: Slack

# 作業内容
- 画面・機能構成
    - ログインページ
    - ユーザー登録ページ
    - プロフィール登録ページ
    - 自己紹介リストページ
    - プロフィール詳細ページ
 
- データ設計
- デザイン
- heroku 設定
- ベース開発
- トップページ = リスト
- 詳細
- 登録ページ

# 次回アクション 集まる時間 来週火曜の授業
- [x] GitHub周りの環境構築
    - アサインは自分にする
    - レビュアーはチームメンバー
    - Approveは２人
- [x] Heroku環境準備
    - URL: aiit-student-profile.herokuapp.com

- [x] CI/CD
    - GitHub Actionを使用する。プルリク時にテストコードを走らせる。
    - RuboCopでコードチェック

- [x] ユーザーストーリー
- [x] ベース開発 
    - @mi-bear 

• この回のみ、プレゼン資料を準備してよい

**Comment by chiroruxx** [comment]
発表が終わっているのでcloseします。
