### ISSUE TITLE
ローカルでdocker build しない環境をつくる

### ISSUE THREAD

**Issue by chiroruxx** [chiroruxx/aiit-student-profile#33]
### 課題
現状は docker build を各自のローカル環境で行っている。

ruby(bundle) はphp(composer)やjavascript(yarn)と違い、ライブラリをプロジェクトディレクトリ配下で管理するのではなく、マシンにインストール形式をとっている。
そのため、依存ライブラリを更新した際には docker build を実行し、インストールする必要がある。
rubyライブラリのインストールに時間がかかるのはもちろんだが、 rubyライブラリのインストール後にnodejsのライブラリもインストールしているためDockerキャッシュが効かず、さらに時間がかかる。

### 対応案
各自がローカルでdocker build をするのをやめ、自動で docker build をしたものを使用する。

以下のようなものを想定している。

1. mainブランチにマージ時にGitHubActionsでdocker イメージをビルドする
2. ビルドしたイメージを [GitHubPackages](https://docs.github.com/ja/packages/learn-github-packages/introduction-to-github-packages) や [DockerHub](https://hub.docker.com/) などのコンテナイメージレジストリにプッシュする
3. ローカルではプッシュされたイメージをプルし、それを利用してコンテナを作成する

これにより、ローカルでは自身でdocker build をする必要がなく、 docker pull を実行するのみで最新のイメージを使用できるため、開発時の待ち時間が減少する。

**Comment by mi-bear** [comment]
ここで build されるのは、main ブランチにあるマージ済みのソースコードってことですか。

**Comment by chiroruxx** [comment]
そうです。マージされていないものは動作保証ができていないものだと思いますので、自動での push はしない想定です。

**Comment by chiroruxx** [comment]
GitHubPackage だと pull する際に `docker login` が必要で面倒なので、 DockerHub を使用する想定。
とりあえずリポジトリは作成した。

https://hub.docker.com/repository/docker/chiroruxx/aiit_student_profule
