### ISSUE TITLE
エラーページをつくる

### ISSUE THREAD

**Issue by chiroruxx** [chiroruxx/aiit-student-profile#47]
エラーページがRailsのデフォルトのものなので、作成する

**Comment by chiroruxx** [comment]
静的ファイルでやるとつらそうなので、動的にやりたい。

ここらへんが一番シンプル？
https://stackoverflow.com/questions/24235805/rails-how-do-i-create-a-custom-404-error-page-that-uses-the-asset-pipeline

**Comment by AkihiroTokai** [comment]
404とかが工夫されているWeb page好きなのですがなんかないですかね。

**Comment by chiroruxx** [comment]
そうですね。とりあえずデザイン通りに作ろうと思ってますが、余力があれば工夫されてるやつにしてもいいかもですね。

個人的には Figma のやつが好きです。
https://note.com/hikarutayama/n/n6e477eabdcd3
