### ISSUE TITLE
Googleログイン時のログインアイコンをプロフィールアイコンに使用する

### ISSUE THREAD

**Issue by ebisennet** [chiroruxx/aiit-student-profile#49]
ユーザー一覧画面等で他人のアイコンが表示できるか確認する。

- [x] 一覧ページの差し替え
- [x] 詳細ページの差し替え

**Comment by chiroruxx** [comment]
https://aiitteam4.slack.com/archives/C02QQU7FE6B/p1642747301001100

<img width="904" alt="image" src="https://user-images.githubusercontent.com/9111423/150479644-1bab754c-586f-4114-8fd3-993ec97a9d5f.png">
