### ISSUE TITLE
GitHub Action のテスト実行時に test 用 credential を読み込む

### ISSUE THREAD

**Issue by mi-bear** [chiroruxx/aiit-student-profile#51]
ref: https://zenn.dev/banrih/articles/f22f0a70bbead2a02110

key: config/credentials/test.key

**Comment by chiroruxx** [comment]
@mi-bear mainブランチにないファイルだと思いますので、そのファイルの存在するブランチ名もくださいー。

**Comment by mi-bear** [comment]
https://github.com/chiroruxx/aiit-student-profile/pull/46
`feature/implementation-google-auth` branch の f369af60339f2e918e5c93910ee1509d2e6838c1 こいつです...！！

**Comment by chiroruxx** [comment]
@mi-bear とりあえず上記のファイルの中身を `RAILS_MASTER_KEY` として設定しました。

![Actions_secrets](https://user-images.githubusercontent.com/9111423/149329735-8f06c301-cb7b-42d1-82da-680195ec3d7d.png)


おそらくこれだけだと環境変数として設定されないと思うので、 GitHubAction内でこいつを環境変数に設定する必要があると思われです。

```yml
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
```

こんな感じです。

これを設定して問題なくクレデンシャルを読み込めるか試してみてくださいー
