### ISSUE TITLE
プロフィール詳細ページが左に寄っているのでコンテンツを真ん中に置く

### ISSUE THREAD

**Issue by chiroruxx** [chiroruxx/aiit-student-profile#53]
![](https://user-images.githubusercontent.com/9111423/148628853-abde14a7-6028-420f-a25e-5c3178d2d014.png)

コンテンツが全体的に左に寄っているので、中央に配置する。
たぶん flex box の css を1行変更するだけでいける

**Comment by ebisennet** [comment]
途中
![image](https://user-images.githubusercontent.com/8840934/149640021-d4a03053-4273-4767-874c-61a61b2fb665.png)
お試し中
※　.base_profileだとメールアドレスまでがセンタリング
※ .profile_two_column_layoutはmada
https://www.webcreatorbox.com/tech/css-flexbox-cheat-sheet
