### ISSUE TITLE
URL設計

### ISSUE THREAD

**Issue by chiroruxx** [chiroruxx/aiit-student-profile#54]
URLが統一感取れていないので、設計してルーティングを修正する

**Comment by mi-bear** [comment]
いいね！っておもいました！

**Comment by chiroruxx** [comment]
URL案

| page | url |
| --- | --- |
| login | / |
| 一覧 | list |
| 詳細 | {id} |
| 作成/編集 | edit |

**Comment by chiroruxx** [comment]
あ、これ id の部分が `400` とかと競合するからダメだな

**Comment by chiroruxx** [comment]
修正版URL案

| page | url |
| --- | --- |
| login | / |
| 一覧 | profiles |
| 詳細 | profiles/{id} |
| 作成/編集 | profiles/edit |
