### ISSUE TITLE
Home の実装とテスト

### ISSUE THREAD

**Issue by mi-bear** [chiroruxx/aiit-student-profile#59]
ログイン前 home のテストを書く。(home って結局いきなり 404 でいいんでしたっけ...?)

**Comment by chiroruxx** [comment]
WF で言うところの「ログイン」が Home にあたるのかなと思います。

<img width="769" alt="image" src="https://user-images.githubusercontent.com/9111423/149613788-7614a641-f2bc-4ccf-9af4-891bb71b431e.png">

**Comment by chiroruxx** [comment]
ログインのデザインはこれ
<img width="662" alt="image" src="https://user-images.githubusercontent.com/9111423/149613890-2025d5c9-bcd4-49e6-97e0-bc41c6f1f581.png">
