### ISSUE TITLE
学生として、自分のプロフィールを登録したい。なぜなら、他の人に自分のプロフィールを見てもらいたいからだ。

### ISSUE THREAD

**Issue by chiroruxx** [chiroruxx/aiit-student-profile#6]
- プロフィール登録ページ
- 以下の情報が登録できる
  - 氏名
  - フリー入力

**Comment by polyu-17002407g** [comment]
基本機能 : #25 

TODO：
- [ ] ログインしたユーザに関する機能 → 別issue #50 
- [x] CSS + 登録した後→リストに飛ばす : #34
- [x] エラーメッセージ : #36
- [ ] ~~S3画像（プロフィールの写真） : #44~~
- [ ] 受講した科目の並び方 → 全ての機能の実装が終わったら、時間があれば。

**Comment by polyu-17002407g** [comment]
残っているもの：
CSS・登録した後→リストに飛ばす（リスト #5 ）→ #34
エラーメッセージ
S3画像（プロフィールの写真）
受講した科目の並び方
