### ISSUE TITLE
Product Review 4

### ISSUE THREAD

**Issue by chiroruxx** [chiroruxx/aiit-student-profile#71]

**Comment by mi-bear** [comment]
## KPT
https://jamboard.google.com/d/1_uFpk-wILPbDzyJYwhIHyDiDLNwEwyi5gbvRiZRz1w4/viewer?f=4

- M1 で苦しんだりしましたが、Ubuntu PC に移したらいい感じ。
- 長くつづいた P-R をマージ、リリースができたよ。
- Try にお気持ちが。Nice 心理的安全性！
- なお、前回のふりかえり Try に ○ × をつけました。

## デモ


## GitHub
- Project 
  - https://github.com/chiroruxx/aiit-student-profile/projects/1
- メトリクス
  - https://github.com/chiroruxx/aiit-student-profile/pulse
- Milestone について
  - https://github.com/chiroruxx/aiit-student-profile/milestones
  - Sprint 単位でゴールが定められていて最高〜！
